<?php

namespace Database\Seeders;

use App\Models\PayrollItem;
use Illuminate\Database\Seeder;

class PayrollItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // Earnings
            [
                'code' => 'PI-001',
                'name' => 'Gaji Pokok',
                'description' => 'Gaji pokok bulanan karyawan',
                'type' => 'earning',
                'category' => 'basic_salary',
                'calculation_type' => 'fixed',
                'default_amount' => 5000000,
                'is_taxable' => true,
                'is_recurring' => true,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'code' => 'PI-002',
                'name' => 'Tunjangan Transport',
                'description' => 'Tunjangan transportasi harian',
                'type' => 'earning',
                'category' => 'allowance',
                'calculation_type' => 'fixed',
                'default_amount' => 500000,
                'is_taxable' => true,
                'is_recurring' => true,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'code' => 'PI-003',
                'name' => 'Tunjangan Makan',
                'description' => 'Tunjangan makan harian',
                'type' => 'earning',
                'category' => 'allowance',
                'calculation_type' => 'fixed',
                'default_amount' => 600000,
                'is_taxable' => true,
                'is_recurring' => true,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'code' => 'PI-004',
                'name' => 'Tunjangan Jabatan',
                'description' => 'Tunjangan berdasarkan jabatan',
                'type' => 'earning',
                'category' => 'allowance',
                'calculation_type' => 'fixed',
                'default_amount' => 1000000,
                'is_taxable' => true,
                'is_recurring' => true,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'code' => 'PI-005',
                'name' => 'Tunjangan Keluarga',
                'description' => 'Tunjangan untuk karyawan berkeluarga',
                'type' => 'earning',
                'category' => 'allowance',
                'calculation_type' => 'fixed',
                'default_amount' => 300000,
                'is_taxable' => true,
                'is_recurring' => true,
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'code' => 'PI-006',
                'name' => 'Tunjangan Hari Raya (THR)',
                'description' => 'Tunjangan Hari Raya Keagamaan',
                'type' => 'earning',
                'category' => 'thr',
                'calculation_type' => 'percentage',
                'default_amount' => 0,
                'percentage_base' => 100,
                'is_taxable' => true,
                'is_recurring' => false,
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'code' => 'PI-007',
                'name' => 'Bonus Kinerja',
                'description' => 'Bonus berdasarkan pencapaian kinerja',
                'type' => 'earning',
                'category' => 'bonus',
                'calculation_type' => 'fixed',
                'default_amount' => 0,
                'is_taxable' => true,
                'is_recurring' => false,
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'code' => 'PI-008',
                'name' => 'Lembur',
                'description' => 'Upah lembur per jam',
                'type' => 'earning',
                'category' => 'overtime',
                'calculation_type' => 'fixed',
                'default_amount' => 50000,
                'is_taxable' => true,
                'is_recurring' => false,
                'is_active' => true,
                'sort_order' => 8,
            ],

            // Deductions
            [
                'code' => 'PI-101',
                'name' => 'BPJS Kesehatan (Karyawan)',
                'description' => 'Iuran BPJS Kesehatan bagian karyawan (1%)',
                'type' => 'deduction',
                'category' => 'bpjs_kesehatan',
                'calculation_type' => 'percentage',
                'default_amount' => 0,
                'percentage_base' => 1,
                'is_taxable' => false,
                'is_recurring' => true,
                'is_active' => true,
                'sort_order' => 101,
            ],
            [
                'code' => 'PI-102',
                'name' => 'BPJS Ketenagakerjaan JHT (Karyawan)',
                'description' => 'Iuran JHT bagian karyawan (2%)',
                'type' => 'deduction',
                'category' => 'bpjs_ketenagakerjaan',
                'calculation_type' => 'percentage',
                'default_amount' => 0,
                'percentage_base' => 2,
                'is_taxable' => false,
                'is_recurring' => true,
                'is_active' => true,
                'sort_order' => 102,
            ],
            [
                'code' => 'PI-103',
                'name' => 'BPJS Ketenagakerjaan JP (Karyawan)',
                'description' => 'Iuran Jaminan Pensiun bagian karyawan (1%)',
                'type' => 'deduction',
                'category' => 'bpjs_ketenagakerjaan',
                'calculation_type' => 'percentage',
                'default_amount' => 0,
                'percentage_base' => 1,
                'is_taxable' => false,
                'is_recurring' => true,
                'is_active' => true,
                'sort_order' => 103,
            ],
            [
                'code' => 'PI-104',
                'name' => 'PPh 21',
                'description' => 'Pajak Penghasilan Pasal 21',
                'type' => 'deduction',
                'category' => 'pph21',
                'calculation_type' => 'formula',
                'default_amount' => 0,
                'is_taxable' => false,
                'is_recurring' => true,
                'is_active' => true,
                'sort_order' => 104,
            ],
            [
                'code' => 'PI-105',
                'name' => 'Pinjaman Karyawan',
                'description' => 'Cicilan pinjaman karyawan',
                'type' => 'deduction',
                'category' => 'loan',
                'calculation_type' => 'fixed',
                'default_amount' => 0,
                'is_taxable' => false,
                'is_recurring' => true,
                'is_active' => true,
                'sort_order' => 105,
            ],
            [
                'code' => 'PI-106',
                'name' => 'Potongan Keterlambatan',
                'description' => 'Potongan karena keterlambatan',
                'type' => 'deduction',
                'category' => 'other_deduction',
                'calculation_type' => 'fixed',
                'default_amount' => 25000,
                'is_taxable' => false,
                'is_recurring' => false,
                'is_active' => true,
                'sort_order' => 106,
            ],
            [
                'code' => 'PI-107',
                'name' => 'Potongan Absensi',
                'description' => 'Potongan karena tidak hadir tanpa keterangan',
                'type' => 'deduction',
                'category' => 'other_deduction',
                'calculation_type' => 'fixed',
                'default_amount' => 0,
                'is_taxable' => false,
                'is_recurring' => false,
                'is_active' => true,
                'sort_order' => 107,
            ],
        ];

        foreach ($items as $item) {
            PayrollItem::updateOrCreate(
                ['code' => $item['code']],
                $item
            );
        }
    }
}
