<?php

return [
    'list' => [
        [
            'key' => 'pos',
            'name' => 'Point of Sale',
            'description' => 'Counter operations, transactions, and receipts.',
            'icon' => '🧾',
            'url' => '/pos',
            'status' => 'planning',
            'color' => 'from-rose-200 to-rose-400 text-slate-900',
            'name_key' => 'home.modules.cards.pos.name',
            'description_key' => 'home.modules.cards.pos.description',
        ],
        [
            'key' => 'transactions',
            'name' => 'Transactions',
            'description' => 'POS settlements, cashier shifts, and transaction history.',
            'icon' => '💳',
            'url' => '/transactions',
            'status' => 'design',
            'color' => 'from-fuchsia-200 to-pink-300 text-slate-900',
            'name_key' => 'home.modules.cards.transactions.name',
            'description_key' => 'home.modules.cards.transactions.description',
        ],
        [
            'key' => 'inventory',
            'name' => 'Inventory',
            'description' => 'Stock, procurement, and branch visibility.',
            'icon' => '📦',
            'url' => '/inventory',
            'status' => 'live',
            'color' => 'from-amber-300 to-amber-400 text-slate-950',
            'name_key' => 'home.modules.cards.inventory.name',
            'description_key' => 'home.modules.cards.inventory.description',
        ],
        [
            'key' => 'hr',
            'name' => 'HR Application',
            'description' => 'Employee data, attendance, and payroll management.',
            'icon' => '👥',
            'url' => '/hr',
            'status' => 'design',
            'color' => 'from-sky-300 to-blue-400 text-slate-900',
            'name_key' => 'home.modules.cards.hr.name',
            'description_key' => 'home.modules.cards.hr.description',
        ],
        [
            'key' => 'reports',
            'name' => 'Reports & Analytics',
            'description' => 'Branch KPIs, sales dashboards, and business insights.',
            'icon' => '📊',
            'url' => '#',
            'status' => 'planning',
            'color' => 'from-purple-300 to-violet-400 text-slate-900',
            'name_key' => 'home.modules.cards.reports.name',
            'description_key' => 'home.modules.cards.reports.description',
        ],
        [
            'key' => 'general-setup',
            'name' => 'General Setup',
            'description' => 'Configure branches, locations, and shared master data.',
            'icon' => '⚙️',
            'url' => '/general-setup',
            'status' => 'live',
            'color' => 'from-emerald-300 to-teal-400 text-slate-900',
            'name_key' => 'home.modules.cards.general.name',
            'description_key' => 'home.modules.cards.general.description',
        ],
        // [
        //     'key' => 'procurement',
        //     'name' => 'Procurement',
        //     'description' => 'Purchase requests, supplier contracts, and approvals.',
        //     'icon' => '📝',
        //     'url' => '#',
        //     'status' => 'coming soon',
        //     'color' => 'from-emerald-300 to-teal-400 text-slate-900',
        // ],
    ],
];
