<?php

return [
    'list' => [
        [
            'key' => 'pos',
            'name' => 'Point of Sale',
            'description' => 'Counter operations, transactions, and receipts.',
            'icon' => '🧾',
            'url' => '/pos',
            'status' => 'planning',
            'color' => 'from-rose-200 to-rose-400 text-slate-900',
            'name_key' => 'home.modules.cards.pos.name',
            'description_key' => 'home.modules.cards.pos.description',
        ],
        [
            'key' => 'transactions',
            'name' => 'Transactions',
            'description' => 'POS settlements, cashier shifts, and transaction history.',
            'icon' => '💳',
            'url' => '/transactions',
            'status' => 'design',
            'color' => 'from-fuchsia-200 to-pink-300 text-slate-900',
            'name_key' => 'home.modules.cards.transactions.name',
            'description_key' => 'home.modules.cards.transactions.description',
        ],
        [
            'key' => 'inventory',
            'name' => 'Inventory',
            'description' => 'Stock levels, adjustments, transfers, and catalog management.',
            'icon' => '📦',
            'url' => '/inventory',
            'status' => 'live',
            'color' => 'from-amber-300 to-amber-400 text-slate-950',
            'name_key' => 'home.modules.cards.inventory.name',
            'description_key' => 'home.modules.cards.inventory.description',
        ],
        [
            'key' => 'procurement',
            'name' => 'Procurement',
            'description' => 'Suppliers, purchase orders, goods receipt, and returns.',
            'icon' => '📝',
            'url' => '/procurement',
            'status' => 'live',
            'color' => 'from-lime-300 to-green-400 text-slate-900',
            'name_key' => 'home.modules.cards.procurement.name',
            'description_key' => 'home.modules.cards.procurement.description',
        ],
        [
            'key' => 'hr',
            'name' => 'HR Application',
            'description' => 'Employee data, attendance, and payroll management.',
            'icon' => '👥',
            'url' => '/hr',
            'status' => 'live',
            'color' => 'from-sky-300 to-blue-400 text-slate-900',
            'name_key' => 'home.modules.cards.hr.name',
            'description_key' => 'home.modules.cards.hr.description',
        ],
        [
            'key' => 'reports',
            'name' => 'Reports & Analytics',
            'description' => 'Sales, inventory, and financial reports with insights.',
            'icon' => '📊',
            'url' => '/reports',
            'status' => 'live',
            'color' => 'from-purple-300 to-violet-400 text-slate-900',
            'name_key' => 'home.modules.cards.reports.name',
            'description_key' => 'home.modules.cards.reports.description',
        ],
        [
            'key' => 'general-setup',
            'name' => 'General Setup',
            'description' => 'Users, products, roles, and system configuration.',
            'icon' => '⚙️',
            'url' => '/general-setup',
            'status' => 'live',
            'color' => 'from-emerald-300 to-teal-400 text-slate-900',
            'name_key' => 'home.modules.cards.general.name',
            'description_key' => 'home.modules.cards.general.description',
        ],
    ],
];
